import { FS } from "@yao/runtime";
import { prompt, send, getCode } from "./utils";

/**
 * Generate Process JSON Schema
 * yao run scripts.process.Generate
 */
function Generate() {
  console.log("Generating Process JSON Schema");
  GenerateModel();
  GenerateFS();
  Merge();
}

/**
 * Generate Model definition
 * yao run scripts.process.GenerateModel
 */
function GenerateModel() {
  console.log("Generating Model definition");
  const pmt = prompt("model.yml");
  const content = send(pmt);
  const fs = new FS("app");
  fs.WriteFile(".vscode/types/runtime/process/model.d.ts", getCode(content));
}

/**
 * Generate FS definition
 * yao run scripts.process.GenerateFS
 */
function GenerateFS() {
  console.log("Generating FS definition");
  const pmt = prompt("fs.yml");
  const content = send(pmt);
  const fs = new FS("app");
  fs.WriteFile(".vscode/types/runtime/process/fs.d.ts", getCode(content));
}

/**
 * Generate HTTP definition
 * yao run scripts.process.GenerateHTTP
 */
function GenerateHTTP() {
  console.log("Generating HTTP definition");
  const pmt = prompt("http.yml");
  const content = send(pmt);
  const fs = new FS("app");
  fs.WriteFile(".vscode/types/runtime/process/http.d.ts", getCode(content));
}

/**
 * Merge all Process functions
 * yao run scripts.process.Merge
 */
function Merge() {
  console.log("Merging Process functions");
  const files = ["model.d.ts", "fs.d.ts", "http.d.ts"];
  const fs = new FS("app");

  let source = ``;
  files.forEach((file) => {
    const content = fs.ReadFile(`.vscode/types/runtime/process/${file}`);
    source = `${source}\n//============ ${file} ============\n${content}`;
  });

  // Common functions
  const common =
    "/**\n" +
    " * Execute a process\n" +
    " * @param name the process name\n" +
    " * @param args additional arguments for the process (variadic parameters)\n" +
    " */\n" +
    "export declare function Process(name: `${string}`, ...args: any[]): any;\n";

  fs.WriteFile(
    ".vscode/types/runtime/process/process.ts",
    `// This file is generated by AI\n// Do not modify this file manually\n\n${source}\n${common}`
  );
}
